### ISSUE TITLE
Failed to get album info

### ISSUE THREAD

**Issue by florinsdistortedvision** [SASUKE-DUCK/AppleMusic-Downloader#1]
![image](https://user-images.githubusercontent.com/97384306/177136000-b650e61d-3996-4aa3-aab1-8fd95d5f9ffd.png)

Tried the example too from readme, same result.

**Comment by SASUKE-DUCK** [comment]
Hello, how are you?
Have you set your account cookies and added any cdm?
you need to do this otherwise it will not work

**Comment by florinsdistortedvision** [comment]
Hello, I'm good, hbu?
I forgot to do CDM, my bad. L3 is enough or do I need L1? 
Also, using this (https://github.com/wvdumper/dumper) for L3 is fine for the script?

**Comment by SASUKE-DUCK** [comment]
I have just left a guide in readme

**Comment by florinsdistortedvision** [comment]
Still the same error seem to show up after putting the CDM

**Comment by SASUKE-DUCK** [comment]
cookies when

**Comment by florinsdistortedvision** [comment]
i've put cookies generated by this extension (https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid) in /cookies/cookies.txt 
![image](https://user-images.githubusercontent.com/97384306/177201103-3f8f0351-4abf-4b8c-b5ad-42f4b556ff8b.png)

are these wrong?

**Comment by fabriguzden** [comment]
![image](https://user-images.githubusercontent.com/27593140/177331246-24a84a16-9fb0-49ab-b386-022488acee01.png)
