### ISSUE TITLE
TypeError: a bytes-like object is required, not 'int'

### ISSUE THREAD

**Issue by JemPH** [SASUKE-DUCK/AppleMusic-Downloader#3]
![image](https://user-images.githubusercontent.com/46235805/177227750-a6711ac3-0ce2-4a4f-9595-afec52c5e7d7.png)

**Found issue : line 488, in do_decrypt**
chal = base64.b64encode(wvdecrypt.get_challenge()).decode('utf-8')

**Replacement : line 488, in do_decrypt**
chal = base64.b64encode(str(wvdecrypt.get_challenge()).encode('utf-8')).decode('utf-8')

and also receiving license error. 

![image](https://user-images.githubusercontent.com/46235805/177227956-eb85d4f6-50e6-4b5b-9468-247b387e1d8d.png)

**Comment by SASUKE-DUCK** [comment]
bruh
cdm when

**Comment by JemPH** [comment]
Update : Added CDM > Devices
![image](https://user-images.githubusercontent.com/46235805/177235098-3a847168-6784-4ba2-9424-ff710af202a1.png)

![image](https://user-images.githubusercontent.com/46235805/177235144-1fbe7888-f097-4dd3-b9f8-62878f1a8d54.png)

**Comment by SASUKE-DUCK** [comment]
your cdm leak is deader than her love for you

**Comment by JemPH** [comment]
Thank you for the info! :>
