### ISSUE TITLE
No module named 'pywidevine.L3.cdm.formats.widevine_pssh_data_pb2'

### ISSUE THREAD

**Issue by fabriguzden** [SASUKE-DUCK/AppleMusic-Downloader#4]
![image](https://user-images.githubusercontent.com/27593140/177280903-e10e1408-251f-4337-b314-a90c6d5a3b04.png)

i get this error
but also another question, in cookies.txt what should I put? Will it be the info in the media-user-token section generated by the chrome cookie generator extension?
I need some own or filtered cdm like device_private_key and device_client_id_blob ???

**Comment by SASUKE-DUCK** [comment]
oka oniros

 ![oniros](https://i.ibb.co/hc5j6R8/unknown-6.png)

https://github.com/SASUKE-DUCK/AppleMusic-Downloader/tree/main/pywidevine/L3/cdm/formats

**Comment by fabriguzden** [comment]
> oka oniros
> 
> ![oniros](https://camo.githubusercontent.com/bc08a79a2efd5af0e95ded3a0dd9bf0c451ca5d9532821007dacceb575e6f7fc/68747470733a2f2f692e6962622e636f2f6863356a3652382f756e6b6e6f776e2d362e706e67)
> 
> https://github.com/SASUKE-DUCK/AppleMusic-Downloader/tree/main/pywidevine/L3/cdm/formats

thank you very much, it's working for me
