### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'temp\\aria2c_infile.txt'

### ISSUE THREAD

**Issue by glomatico** [SASUKE-DUCK/AppleMusic-Downloader#6]
I am getting this error while trying to download a song.

```
[10:23:53] INFO: + Starting Apple Music Ripper
[10:23:54] INFO: + Downloading 1 - Michael Jackson - Bad..
[10:23:54] INFO: + Downloading Audio Track
Traceback (most recent call last):
  File "C:\Users\glomatico\Downloads\AppleMusic-Downloader-main\applemusic.py", line 721, in <module>
    client.run(metadata, filename)
  File "C:\Users\glomatico\Downloads\AppleMusic-Downloader-main\applemusic.py", line 613, in run
    self.download_track(enc_tracks)
  File "C:\Users\glomatico\Downloads\AppleMusic-Downloader-main\applemusic.py", line 383, in download_track
    with open(aria2c_infile, 'w') as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'temp\\aria2c_infile.txt'
```

**Comment by thefexcos791** [comment]
add temp folder

**Comment by glomatico** [comment]
Thank you, but after making the temp folder I got a different error.
```
[06:17:58] INFO: + Starting Apple Music Ripper
[06:17:59] INFO: + Downloading 1 - Michael Jackson - Bad..
[06:18:00] INFO: + Downloading Audio Track
[06:18:04] INFO: + Decrypting Audio Track
[06:18:04] INFO: + Fetching Service Certificate...
[06:18:05] INFO: + Requesting license...
[06:18:05] INFO: opening new cdm session
[06:18:05] INFO: session opened and init data parsed successfully
[06:18:05] INFO: getting license request
[06:18:05] ERROR: no client ID blob available for this device
Traceback (most recent call last):
  File "C:\Users\glomatico\Downloads\AppleMusic-Downloader-main\applemusic.py", line 721, in <module>
    client.run(metadata, filename)
  File "C:\Users\glomatico\Downloads\AppleMusic-Downloader-main\applemusic.py", line 619, in run
    success, key = self.do_decrypt(wvdecrypt_config, track)
  File "C:\Users\glomatico\Downloads\AppleMusic-Downloader-main\applemusic.py", line 488, in do_decrypt
    chal = base64.b64encode(wvdecrypt.get_challenge()).decode('utf-8')
  File "C:\Users\glomatico\AppData\Local\Programs\Python\Python310\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'int'
```

**Comment by glomatico** [comment]
ok i actually just forgot to put device_client_id_blob and device_private_key file in pywidevine/L3/cdm/devices/android_generic folder

**Comment by florinsdistortedvision** [comment]
Yo can you share your CDM to me on Twitter ?

**Comment by SASUKE-DUCK** [comment]
kek

**Comment by glomatico** [comment]
> > ok i actually just forgot to put device_client_id_blob and device_private_key file in pywidevine/L3/cdm/devices/android_generic folder
> 
> If i may ask, how did you do that? Thanks!
I used this tool https://github.com/wvdumper/dumper
I just had to rename the files after I dumped.

**Comment by CitricWispy** [comment]
> > > ok i actually just forgot to put device_client_id_blob and device_private_key file in pywidevine/L3/cdm/devices/android_generic folder
> > 
> > If i may ask, how did you do that? Thanks!
> 
> I used this tool https://github.com/wvdumper/dumper to get CDM.
> I just had to rename the files after I dumped and move it to the correct folder.
> I also had to make some modifications in applemusic.py and dumper in order to make both work.
> 

hmm, seems to complicated 😆

**Comment by glomatico** [comment]
> > > > ok i actually just forgot to put device_client_id_blob and device_private_key file in pywidevine/L3/cdm/devices/android_generic folder
> > > 
> > > 
> > > If i may ask, how did you do that? Thanks!
> > 
> > 
> > I used this tool https://github.com/wvdumper/dumper to get CDM.
> > I just had to rename the files after I dumped and move it to the correct folder.
> > I also had to make some modifications in applemusic.py and dumper in order to make both work.
> 
> hmm, seems to complicated 😆

Sure it is. I had to figure out all myself lol.

**Comment by CitricWispy** [comment]
> > > > > ok i actually just forgot to put device_client_id_blob and device_private_key file in pywidevine/L3/cdm/devices/android_generic folder
> > > > 
> > > > 
> > > > If i may ask, how did you do that? Thanks!
> > > 
> > > 
> > > I used this tool https://github.com/wvdumper/dumper to get CDM.
> > > I just had to rename the files after I dumped and move it to the correct folder.
> > > I also had to make some modifications in applemusic.py and dumper in order to make both work.
> > 
> > hmm, seems to complicated 😆
> 
> Sure it is. I had to figure out all myself lol.

Is it ok if you could walk me through the steps of getting it to work? I know it is a little unfair cause you figured it out all by yourself but I'm no expert at these things haha 😅

**Comment by CitricWispy** [comment]
> > > > > > ok i actually just forgot to put device_client_id_blob and device_private_key file in pywidevine/L3/cdm/devices/android_generic folder
> > > > > 
> > > > > 
> > > > > If i may ask, how did you do that? Thanks!
> > > > 
> > > > 
> > > > I used this tool https://github.com/wvdumper/dumper to get CDM.
> > > > I just had to rename the files after I dumped and move it to the correct folder.
> > > > I also had to make some modifications in applemusic.py and dumper in order to make both work.
> > > 
> > > hmm, seems to complicated 😆
> > 
> > Sure it is. I had to figure out all myself lol.
> 
> Is it ok if you could walk me through the steps of getting it to work? I know it is a little unfair cause you figured it out all by yourself but I'm no expert at these things haha 😅
> 

I can give you my discord if you have it :)
